---
# tasks file for ec2_creation
- name: Create instance
  ec2:
    region: "{{ec2_config.region}}"
    zone: "{{ec2_config.zone}}"
    keypair: "{{ec2_config.keypair}}"
    instance_type: "{{ec2_config.instance_type}}"
    image: "{{ec2_config.image}}"
    vpc_subnet_id: "{{ec2_config.vpc_subnet_id}}"
    group: "{{ec2_config.group}}"
    assign_public_ip: "{{ec2_config.assign_public_ip}}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ec2_config.volume_size}}"
        delete_on_termination: true   
    count: 1    
    wait: yes    
    instance_tags:
      Name: "{{ec2_config.instance_tag_name}}" 
  register: ec2

- name: Debug instances 
  debug: msg="{{ ec2.instances[0] }}"

- name: Wait for instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
  when: ec2|changed   
    
- name: Add new instance to virtual ec2hosts host group
  add_host: hostname={{ ec2.instances[0].public_ip }} groupname=ec2hosts ansible_ssh_user="{{ec2_config.remote_user}}" ansible_ssh_port=22 ansible_ssh_private_key_file="{{ec2_config.ssh_path}}"
  with_items: ec2_instances.instances 
